services:
  db:
    image: postgres:latest
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
